# Lints changes with Prettier
name: prettier-lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install and run Prettier on all files
        run: npm install --save-dev --save-exact prettier
        run: prettier --config ./.prettierrc.json --write .
