# Lints changes with Prettier
name: prettier-lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: unbuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2
      - name: Run Prettier
        uses: wearerequired/lint-action@v1.10.0
        with:
          prettier: true
